[k8s:children]
cp
nodes

[k8s:vars]
primary=false

[cp]
192.168.1.253 hostname=cp1 primary=true
; 192.168.1.12 hostname=cp2

[cp:vars]
node_role=cp

[nodes]
192.168.1.185 hostname=node1
192.168.1.100 hostname=node2
192.168.1.114 hostname=node3
192.168.1.206 hostname=node4

[nodes:vars]
node_role=node
