apiVersion: v1
kind: Service
metadata:
  name: nginx-srv
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8080 # Service Listening Port
      targetPort: 80 # Pod Listening Port
