---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: web
  template: # CONFIG DO POD
    metadata:
      labels:
        tier: web
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: tier
              value: "web"
