---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.1
    helm:
      releaseName: ingress-nginx
      parameters:
        - name: "controller.service.type"
          value: LoadBalancer
        - name: "controller.extraArgs.enable-ssl-passthrough"
          value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:  # automatic sync options
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foregroud
      - PruneLast=true
