################################################################################
#
# Control-plane initial installation
#
################################################################################
- name: Check if kubernetes config file exists
  become: true
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_config_file
  tags:
    - init

- name: Init kubernetes cluster
  become: true
  ansible.builtin.command:
    cmd: kubeadm init
  register: k8s_init
  changed_when: k8s_init.rc == 0
  when: not k8s_config_file.stat.exists
  tags:
    - init

- name: Create ~/.kube directory.
  become: true
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0755"
  tags:
    - init

- name: Configure kube config.
  become: true
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: "0644"
  tags:
    - init

- name: Configure kubectl auto completion.
  become: true
  ansible.builtin.shell:
    cmd: echo "source <(kubectl completion bash)" >> ~/.bashrc
  register: config_auto_completion
  failed_when: config_auto_completion.rc != 0
  changed_when: false
  tags:
    - init

- name: Get latest weave_net release
  ansible.builtin.uri:
    url: "https://api.github.com/repos/weaveworks/weave/releases/latest"
    method: GET
  register: latest_weave_net_release
  when: weave_net_upgrade == "true"
  tags:
    - init

- name: Set version of weave_net to latest.
  ansible.builtin.set_fact:
    weave_net_version: "{{ latest_weave_net_release.json.tag_name | replace('v', '') }}"
  when: weave_net_upgrade == "true"
  tags:
    - init

- name: Get weave_net yaml
  ansible.builtin.uri:
    url: "{{ weave_net_url }}"
    return_content: true
  register: weave_net_url_yaml
  tags:
    - init

- name: Set the wave_net image to version {{ weave_net_version }}
  ansible.builtin.set_fact:
    weave_net_yaml: "{{ weave_net_url_yaml.content | replace(':latest', ':' ~ weave_net_version) }}"
  when: weave_net_url_yaml is defined
  tags:
    - init

- name: Save weave_net.yaml to file
  ansible.builtin.copy:
    content: "{{ weave_net_yaml }}"
    dest: "{{ weave_net_yaml_path }}"
    mode: "0644"
    force: "true"
  when: weave_net_yaml is defined
  tags:
    - init

- name: Install CNI (Weave Net)
  become: true
  ansible.builtin.command:
    cmd: kubectl apply -f {{ weave_net_yaml_path }}
  register: install_cni_weave
  changed_when: "'created' in install_cni_weave.stdout"
  failed_when: install_cni_weave.rc != 0
  when: k8s_cni == "weave"
  tags:
    - init

- name: Configure localy the access to kubectl
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: true
  tags:
    - init
