################################################################################
#
# Node join cluster
#
################################################################################
- name: Get the kubeadm join command from the Kubernetes control-plane.
  become: true
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  changed_when: false
  when: primary == "true"
  register: kubeadm_token_create_result
  tags:
    - nodes

- name: Configure kubeadm join command to all nodes.
  become: true
  ansible.builtin.set_fact:
    k8s_join_cmd: "{{ kubeadm_token_create_result.stdout }}"
  when: kubeadm_token_create_result.stdout is defined
  delegate_facts: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"
  tags:
    - nodes

- name: Check if kubelet already configured
  become: true
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_config_file
  when: node_role == "node"
  tags:
    - nodes

- name: Node join in cluster
  become: true
  ansible.builtin.command:
    cmd: "{{ hostvars[inventory_hostname].k8s_join_cmd }}"
  register: join_command
  changed_when: join_command.rc != 0
  when: node_role == "node" and not kubelet_config_file.stat.exists
  tags:
    - nodes
