---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-web-app
  namespace: argocd  # same namespace as argocd
  finalizers:
    # remove all resources when remove from argocd
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/marcellmartini/devops-tools.git
    targetRevision: add-argocd
    path: apps/apps/go-web/helm/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foregroud
      - PruneLast=true
