---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd # same namespace as argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marcellmartini/devops-tools
    targetRevision: add-gitops
    path: gitops/argocd/gitops_folder/1-app
  destination:
    server: https://kubernetes.default.svc
