---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-d
  namespace: argocd # same namespace as argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.17.2
    chart: istiod
    helm:
      version: v3
      releaseName: my-istio-d
      passCredentials: false
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foregroud
      - PruneLast=true
