---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: install-ingress-nginx
  namespace: argocd  # same namespace as argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MatheusVictor23/devops-tools.git #monitora esse git
    path: ingress/nginx/helm/ //executa esse helm
  destination:
    server: https://kubernetes.default.svc #aplica o helm nesse service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:  # automatic sync options
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foregroud
      - PruneLast=true
