apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr1
subjects:
  - kind: ServiceAccount
    name: reader
    namespace: default
