---
replicaCount: 1
name: go-web-app
env: dev
namespace: dev
fqdn: goweb.192.168.49.2.nip.io
image:
  name: go-web
  tag: 'dev'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  portName: http
