---
# defaults file for teste
k8s_version: "1.26.4"
k8s_cni: "weave"
weave_net_yaml: https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
hostname: ""
node_role: "node"
primary: "false"
