---
# Standard Argo CD installation with cluster-admin access
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base/namespace.yaml
  - ./base/repository.yaml
  - ./base/secrets.yaml
  - ./base/ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.7/manifests/install.yaml

patches:
  - path: ./overlays/service.yaml
  - path: ./overlays/argocd-secret.yaml

namespace: argocd
