---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-deployment
  namespace: {{ .Values.namespace }}
  annotations:
    codefresh.io/app: simple-go-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "marcellmartini/go-web:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
