apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: default
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        istio-injection: enabled
    syncOptions:
      - CreateNamespace=true
