name: Terratest Kind Cluster
on:
  pull_request:
      paths:
        - k8s/clusters/kind
jobs:
  go-tests:
    name: Run Kind Creation Cluster Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.20"
      - name: Download Go Modules
        working-directory: k8s/clusters/kind/test
        run: go mod tidy
      - name: Run Go Tests
        working-directory: ./
        run: make kind-cluster-test
